import type { CatalogCollections } from "@/lib/types";
import {
  COLOR_PRICE_BY_NAME,
  HEIGHT_MULTIPLIER_BY_VALUE_M,
  PANEL_PRICE_BY_PATTERN,
  POST_PRICE_BY_SLUG,
  SPACER_PRICE_BY_NAME,
} from "@/lib/pricing/variant-prices";

/** Dane demo gdy Firebase nie jest skonfigurowany (dev bez .env.local). */
export const MOCK_CATALOG: CatalogCollections = {
  posts: [
    {
      id: "post-1",
      name: "Profil 60×40 mm",
      slug: "standard",
      widthCm: 10,
      priceSurchargePerMeter: POST_PRICE_BY_SLUG.standard,
      sortOrder: 0,
      active: true,
    },
    {
      id: "post-2",
      name: "Profil 80×40 mm",
      slug: "reinforced",
      widthCm: 12,
      priceSurchargePerMeter: POST_PRICE_BY_SLUG.reinforced,
      sortOrder: 1,
      active: true,
    },
  ],
  panels: [
    {
      id: "panel-1",
      name: "Panel 3D",
      patternId: "pattern-3d",
      priceSurchargePerMeter: PANEL_PRICE_BY_PATTERN["pattern-3d"],
      sortOrder: 0,
      active: true,
    },
    {
      id: "panel-2",
      name: "Palisada",
      patternId: "pattern-palisade",
      priceSurchargePerMeter: PANEL_PRICE_BY_PATTERN["pattern-palisade"],
      sortOrder: 1,
      active: true,
    },
  ],
  spacerOptions: [
    {
      id: "spacer-1",
      name: "Ocynk",
      hasSpacer: false,
      openness: 0,
      priceSurchargePerMeter: SPACER_PRICE_BY_NAME.Ocynk,
      sortOrder: 0,
      active: true,
    },
    {
      id: "spacer-2",
      name: "Malowanie proszkowe RAL",
      hasSpacer: false,
      openness: 0.15,
      priceSurchargePerMeter: SPACER_PRICE_BY_NAME["Malowanie proszkowe RAL"],
      sortOrder: 1,
      active: true,
    },
  ],
  heights: [
    {
      id: "h-1",
      label: "1,53 m",
      valueM: 1.53,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[1.53],
      sortOrder: 0,
      active: true,
    },
    {
      id: "h-2",
      label: "1,80 m",
      valueM: 1.8,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[1.8],
      sortOrder: 1,
      active: true,
    },
    {
      id: "h-3",
      label: "2,00 m",
      valueM: 2.0,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[2],
      sortOrder: 2,
      active: true,
    },
  ],
  colors: [
    {
      id: "c-1",
      name: "Ocynk naturalny",
      hex: "#a8b0b8",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["Ocynk naturalny"],
      sortOrder: 0,
      active: true,
    },
    {
      id: "c-2",
      name: "RAL 6005 zielony",
      hex: "#0f5132",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["RAL 6005 zielony"],
      sortOrder: 1,
      active: true,
    },
    {
      id: "c-3",
      name: "RAL 7016 grafit",
      hex: "#383e42",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["RAL 7016 grafit"],
      sortOrder: 2,
      active: true,
    },
    {
      id: "c-4",
      name: "RAL 9005 czarny",
      hex: "#1a1a18",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["RAL 9005 czarny"],
      sortOrder: 3,
      active: true,
    },
    {
      id: "c-5",
      name: "RAL 9002 biały",
      hex: "#f0f0eb",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["RAL 9002 biały"],
      sortOrder: 4,
      active: true,
    },
  ],
  elements: [
    {
      id: "el-brama-1",
      type: "brama",
      name: "Brama przesuwna",
      priceNet: 2200,
      sortOrder: 0,
      active: true,
    },
    {
      id: "el-brama-2",
      type: "brama",
      name: "Brama przesuwna palisadowa",
      priceNet: 3700,
      sortOrder: 1,
      active: true,
    },
    {
      id: "el-brama-3",
      type: "brama",
      name: "Brama dwuskrzydłowa",
      priceNet: 1200,
      sortOrder: 2,
      active: true,
    },
    {
      id: "el-brama-4",
      type: "brama",
      name: "Brama dwuskrzydłowa palisadowa",
      priceNet: 2700,
      sortOrder: 3,
      active: true,
    },
    {
      id: "el-furtka-1",
      type: "furtka",
      name: "Furtka panelowa",
      priceNet: 520,
      sortOrder: 0,
      active: true,
    },
    {
      id: "el-furtka-2",
      type: "furtka",
      name: "Furtka palisadowa",
      priceNet: 900,
      sortOrder: 1,
      active: true,
    },
    {
      id: "el-furtka-3",
      type: "furtka",
      name: "Klamka + zamek",
      priceNet: 80,
      sortOrder: 2,
      active: true,
    },
  ],
  panelTextures: [],
  postTextures: [],
};
