import type { CatalogCollections } from "@/lib/types";
import {
  COLOR_PRICE_BY_NAME,
  FOOTING_HEIGHT_SURCHARGE_BY_CM,
  FOOTING_MATERIAL_SURCHARGE_BY_NAME,
  HEIGHT_MULTIPLIER_BY_VALUE_M,
  PANEL_PRICE_BY_PATTERN,
  POST_PRICE_BY_SLUG,
  SPACER_PRICE_BY_NAME,
} from "@/lib/pricing/variant-prices";

/** Dane demo gdy Firebase nie jest skonfigurowany (dev bez .env.local). */
export const MOCK_CATALOG: CatalogCollections = {
  posts: [
    {
      id: "post-1",
      name: "Profil 60×40 mm",
      slug: "standard",
      widthCm: 10,
      priceSurchargePerMeter: POST_PRICE_BY_SLUG.standard,
      priceSurchargePerPanel: POST_PRICE_BY_SLUG.standard,
      sortOrder: 0,
      active: true,
    },
    {
      id: "post-2",
      name: "Profil 80×40 mm",
      slug: "reinforced",
      widthCm: 12,
      priceSurchargePerMeter: POST_PRICE_BY_SLUG.reinforced,
      priceSurchargePerPanel: POST_PRICE_BY_SLUG.reinforced,
      sortOrder: 1,
      active: true,
    },
  ],
  panels: [
    {
      id: "panel-1",
      name: "Panel 3D",
      patternId: "pattern-3d",
      priceSurchargePerMeter: PANEL_PRICE_BY_PATTERN["pattern-3d"],
      priceSurchargePerPanel: PANEL_PRICE_BY_PATTERN["pattern-3d"],
      sortOrder: 0,
      active: true,
    },
    {
      id: "panel-2",
      name: "Palisada",
      patternId: "pattern-palisade",
      priceSurchargePerMeter: PANEL_PRICE_BY_PATTERN["pattern-palisade"],
      priceSurchargePerPanel: PANEL_PRICE_BY_PATTERN["pattern-palisade"],
      sortOrder: 1,
      active: true,
    },
    {
      id: "panel-3",
      name: "Panel poziomy",
      patternId: "pattern-panel-horizontal",
      priceSurchargePerMeter: PANEL_PRICE_BY_PATTERN["pattern-panel-horizontal"],
      priceSurchargePerPanel: PANEL_PRICE_BY_PATTERN["pattern-panel-horizontal"],
      sortOrder: 2,
      active: true,
    },
  ],
  spacerOptions: [
    {
      id: "spacer-1",
      name: "Ocynk",
      hasSpacer: false,
      openness: 0,
      priceSurchargePerMeter: SPACER_PRICE_BY_NAME.Ocynk,
      priceSurchargePerPanel: SPACER_PRICE_BY_NAME.Ocynk,
      sortOrder: 0,
      active: true,
    },
    {
      id: "spacer-2",
      name: "Malowanie proszkowe RAL",
      hasSpacer: false,
      openness: 0.15,
      priceSurchargePerMeter: SPACER_PRICE_BY_NAME["Malowanie proszkowe RAL"],
      priceSurchargePerPanel: SPACER_PRICE_BY_NAME["Malowanie proszkowe RAL"],
      sortOrder: 1,
      active: true,
    },
  ],
  heights: [
    {
      id: "h-1",
      label: "1,53 m",
      valueM: 1.53,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[1.53],
      sortOrder: 0,
      active: true,
    },
    {
      id: "h-2",
      label: "1,80 m",
      valueM: 1.8,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[1.8],
      sortOrder: 1,
      active: true,
    },
    {
      id: "h-3",
      label: "2,00 m",
      valueM: 2.0,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[2],
      sortOrder: 2,
      active: true,
    },
  ],
  colors: [
    {
      id: "c-1",
      name: "Ocynk naturalny",
      hex: "#a8b0b8",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["Ocynk naturalny"],
      priceSurchargePerPanel: COLOR_PRICE_BY_NAME["Ocynk naturalny"],
      sortOrder: 0,
      active: true,
    },
    {
      id: "c-2",
      name: "RAL 6005 zielony",
      hex: "#0f5132",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["RAL 6005 zielony"],
      priceSurchargePerPanel: COLOR_PRICE_BY_NAME["RAL 6005 zielony"],
      sortOrder: 1,
      active: true,
    },
    {
      id: "c-3",
      name: "RAL 7016 grafit",
      hex: "#383e42",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["RAL 7016 grafit"],
      priceSurchargePerPanel: COLOR_PRICE_BY_NAME["RAL 7016 grafit"],
      sortOrder: 2,
      active: true,
    },
    {
      id: "c-4",
      name: "RAL 9005 czarny",
      hex: "#1a1a18",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["RAL 9005 czarny"],
      priceSurchargePerPanel: COLOR_PRICE_BY_NAME["RAL 9005 czarny"],
      sortOrder: 3,
      active: true,
    },
    {
      id: "c-5",
      name: "RAL 9002 biały",
      hex: "#f0f0eb",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["RAL 9002 biały"],
      priceSurchargePerPanel: COLOR_PRICE_BY_NAME["RAL 9002 biały"],
      sortOrder: 4,
      active: true,
    },
  ],
  footingHeights: [
    {
      id: "fh-1",
      label: "20 cm",
      heightCm: 20,
      priceSurchargePerPanel: FOOTING_HEIGHT_SURCHARGE_BY_CM[20],
      sortOrder: 0,
      active: true,
    },
    {
      id: "fh-2",
      label: "30 cm",
      heightCm: 30,
      priceSurchargePerPanel: FOOTING_HEIGHT_SURCHARGE_BY_CM[30],
      sortOrder: 1,
      active: true,
    },
    {
      id: "fh-3",
      label: "40 cm",
      heightCm: 40,
      priceSurchargePerPanel: FOOTING_HEIGHT_SURCHARGE_BY_CM[40],
      sortOrder: 2,
      active: true,
    },
  ],
  footingMaterials: [
    {
      id: "fm-1",
      name: "Beton szary",
      hex: "#9ca3af",
      priceSurchargePerPanel: FOOTING_MATERIAL_SURCHARGE_BY_NAME["Beton szary"],
      sortOrder: 0,
      active: true,
    },
    {
      id: "fm-2",
      name: "Klinkier czerwony",
      hex: "#8b3a2a",
      priceSurchargePerPanel:
        FOOTING_MATERIAL_SURCHARGE_BY_NAME["Klinkier czerwony"],
      sortOrder: 1,
      active: true,
    },
    {
      id: "fm-3",
      name: "Stal malowana RAL",
      hex: "#383e42",
      priceSurchargePerPanel:
        FOOTING_MATERIAL_SURCHARGE_BY_NAME["Stal malowana RAL"],
      sortOrder: 2,
      active: true,
    },
  ],
  elements: [
    {
      id: "el-brama-1",
      type: "brama",
      name: "Brama przesuwna panelowa",
      gateKind: "sliding",
      infillPatternId: "pattern-3d",
      priceNet: 2200,
      sortOrder: 0,
      active: true,
    },
    {
      id: "el-brama-5",
      type: "brama",
      name: "Brama przesuwna pozioma",
      gateKind: "sliding",
      infillPatternId: "pattern-panel-horizontal",
      priceNet: 2800,
      sortOrder: 1,
      active: true,
    },
    {
      id: "el-brama-2",
      type: "brama",
      name: "Brama przesuwna palisadowa",
      gateKind: "sliding",
      infillPatternId: "pattern-palisade",
      priceNet: 3700,
      sortOrder: 2,
      active: true,
    },
    {
      id: "el-brama-3",
      type: "brama",
      name: "Brama dwuskrzydłowa panelowa",
      gateKind: "double-leaf",
      infillPatternId: "pattern-3d",
      priceNet: 1200,
      sortOrder: 3,
      active: true,
    },
    {
      id: "el-brama-6",
      type: "brama",
      name: "Brama dwuskrzydłowa pozioma",
      gateKind: "double-leaf",
      infillPatternId: "pattern-panel-horizontal",
      priceNet: 1800,
      sortOrder: 4,
      active: true,
    },
    {
      id: "el-brama-4",
      type: "brama",
      name: "Brama dwuskrzydłowa palisadowa",
      gateKind: "double-leaf",
      infillPatternId: "pattern-palisade",
      priceNet: 2700,
      sortOrder: 5,
      active: true,
    },
    {
      id: "el-furtka-1",
      type: "furtka",
      name: "Furtka panelowa",
      priceNet: 520,
      sortOrder: 0,
      active: true,
    },
    {
      id: "el-furtka-2",
      type: "furtka",
      name: "Furtka palisadowa",
      priceNet: 900,
      sortOrder: 1,
      active: true,
    },
    {
      id: "el-furtka-3",
      type: "furtka",
      name: "Klamka + zamek",
      priceNet: 80,
      sortOrder: 2,
      active: true,
    },
  ],
  panelTextures: [],
  postTextures: [],
};
