import type { CatalogCollections } from "@/lib/types";
import {
  COLOR_PRICE_BY_NAME,
  HEIGHT_MULTIPLIER_BY_VALUE_M,
  PANEL_PRICE_BY_PATTERN,
  POST_PRICE_BY_SLUG,
  SPACER_PRICE_BY_NAME,
} from "@/lib/pricing/variant-prices";

/** Dane demo gdy Firebase nie jest skonfigurowany (dev bez .env.local). */
export const MOCK_CATALOG: CatalogCollections = {
  posts: [
    {
      id: "post-1",
      name: "Słupek standard",
      slug: "standard",
      widthCm: 20,
      priceSurchargePerMeter: POST_PRICE_BY_SLUG.standard,
      sortOrder: 0,
      active: true,
    },
    {
      id: "post-2",
      name: "Słupek dekoracyjny",
      slug: "dekor",
      widthCm: 25,
      priceSurchargePerMeter: POST_PRICE_BY_SLUG.dekor,
      sortOrder: 1,
      active: true,
    },
  ],
  panels: [
    {
      id: "panel-1",
      name: "Gładki",
      patternId: "pattern-solid",
      priceSurchargePerMeter: PANEL_PRICE_BY_PATTERN["pattern-solid"],
      sortOrder: 0,
      active: true,
    },
    {
      id: "panel-2",
      name: "Pionowe linie",
      patternId: "pattern-lines",
      priceSurchargePerMeter: PANEL_PRICE_BY_PATTERN["pattern-lines"],
      sortOrder: 1,
      active: true,
    },
    {
      id: "panel-3",
      name: "Siatka",
      patternId: "pattern-grid",
      priceSurchargePerMeter: PANEL_PRICE_BY_PATTERN["pattern-grid"],
      sortOrder: 2,
      active: true,
    },
    {
      id: "panel-4",
      name: "Cegiełka",
      patternId: "pattern-brick",
      priceSurchargePerMeter: PANEL_PRICE_BY_PATTERN["pattern-brick"],
      sortOrder: 3,
      active: true,
    },
  ],
  spacerOptions: [
    {
      id: "spacer-1",
      name: "Bez dystansu (pełne)",
      hasSpacer: false,
      openness: 0,
      priceSurchargePerMeter: SPACER_PRICE_BY_NAME["Bez dystansu (pełne)"],
      sortOrder: 0,
      active: true,
    },
    {
      id: "spacer-2",
      name: "Z dystansem (ażurowe)",
      hasSpacer: true,
      openness: 0.35,
      priceSurchargePerMeter: SPACER_PRICE_BY_NAME["Z dystansem (ażurowe)"],
      sortOrder: 1,
      active: true,
    },
  ],
  heights: [
    {
      id: "h-1",
      label: "1,00 m",
      valueM: 1.0,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[1],
      sortOrder: 0,
      active: true,
    },
    {
      id: "h-2",
      label: "1,50 m",
      valueM: 1.5,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[1.5],
      sortOrder: 1,
      active: true,
    },
    {
      id: "h-3",
      label: "1,75 m",
      valueM: 1.75,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[1.75],
      sortOrder: 2,
      active: true,
    },
    {
      id: "h-4",
      label: "2,00 m",
      valueM: 2.0,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[2],
      sortOrder: 3,
      active: true,
    },
    {
      id: "h-5",
      label: "2,25 m",
      valueM: 2.25,
      priceMultiplier: HEIGHT_MULTIPLIER_BY_VALUE_M[2.25],
      sortOrder: 4,
      active: true,
    },
  ],
  colors: [
    {
      id: "c-1",
      name: "Szary naturalny",
      hex: "#9ca3af",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["Szary naturalny"],
      sortOrder: 0,
      active: true,
    },
    {
      id: "c-2",
      name: "Antracyt",
      hex: "#374151",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME.Antracyt,
      sortOrder: 1,
      active: true,
    },
    {
      id: "c-3",
      name: "Biały",
      hex: "#f3f4f6",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME.Biały,
      sortOrder: 2,
      active: true,
    },
    {
      id: "c-4",
      name: "Piaskowy",
      hex: "#d6c4a8",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME.Piaskowy,
      sortOrder: 3,
      active: true,
    },
    {
      id: "c-5",
      name: "Grafit",
      hex: "#4b5563",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME.Grafit,
      sortOrder: 4,
      active: true,
    },
    {
      id: "c-6",
      name: "Czerwony cegła",
      hex: "#b45309",
      priceSurchargePerMeter: COLOR_PRICE_BY_NAME["Czerwony cegła"],
      sortOrder: 5,
      active: true,
    },
  ],
  elements: [
    {
      id: "el-brama",
      type: "brama",
      name: "Brama wjazdowa",
      priceNet: 1000,
      sortOrder: 0,
      active: true,
    },
    {
      id: "el-furtka-90",
      type: "furtka",
      name: "Furtka 90 cm",
      priceNet: 300,
      sortOrder: 0,
      active: true,
    },
    {
      id: "el-furtka-110",
      type: "furtka",
      name: "Furtka 110 cm",
      priceNet: 500,
      sortOrder: 1,
      active: true,
    },
  ],
  panelTextures: [],
  postTextures: [],
};
